extends: default

rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
    indent-sequences: consistent
  trailing-spaces: enable
  key-duplicates: enable
  document-start: disable
  document-end: disable
