name: "Kubernetes Deployment Tester"
description: "Deploy an application to Kind and make a simple HTTP test to test the deployment."
author: "Alexandru Arvinte"
branding:
  icon: "box"
  color: "green"
inputs:
  image-name:
    description: "Full image name (repo/image_name:tag)"
    required: true
  port:
    description: "Application port"
    required: true
  github-token:
    description: "GitHub token, you can use the default token: secrets.GITHUB_TOKEN"
    required: true
  timeout:
    description: "Time to out until testing the pod"
    required: false
    default: "20s"

runs:
  using: "composite"
  steps:
    - run: |
        echo "
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: test
        " > sa.yaml
      shell: bash

    - run: |
        echo "
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: test
        subjects:
        - kind: ServiceAccount
          name: test
          namespace: default
        roleRef:
          kind: ClusterRole
          name: cluster-admin
          apiGroup: rbac.authorization.k8s.io
        " > crb.yaml
      shell: bash

    - run: |
        echo "
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: application
          labels:
            app: application
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: application
          template:
            metadata:
              labels:
                app: application
            spec:
              containers:
              - name: application
                image: ${{ inputs.image-name }}
                ports:
                - containerPort: ${{ inputs.port }}
                readinessProbe:
                  httpGet:
                    path: /
                    port: ${{ inputs.port }}
                  initialDelaySeconds: 5
                  periodSeconds: 10
                livenessProbe:
                  httpGet:
                    path: /
                    port: ${{ inputs.port }}
                  initialDelaySeconds: 15
                  periodSeconds: 20
              imagePullSecrets:
              - name: ghcr-secret
        " > deployment.yaml
      shell: bash

    - name: Setup Kind
      uses: helm/kind-action@v1.2.0

    - run: |
        kubectl cluster-info
        kubectl get nodes
      shell: bash

    - run: |
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ inputs.github-token }}
      shell: bash

    - run: |
        kubectl apply -f sa.yaml
        kubectl apply -f crb.yaml
        kubectl apply -f deployment.yaml
        echo "Sleeping for ${{ inputs.timeout }} to allow the pod to fully start."
        sleep ${{ inputs.timeout }}
        kubectl get po
        POD_NAME=$(kubectl get pod -l app=application -o jsonpath="{.items[0].metadata.name}")
        kubectl port-forward $POD_NAME 8000:${{ inputs.port }} &>/dev/null &
        sleep 5
      shell: bash

    - run: |
        curl -i http://localhost:8000/
      shell: bash
