name: "Kubernetes Deployment Tester"
description: "Deploy an application to Kind and make a simple HTTP test to test the deployment."
author: "Alexandru Arvinte"
branding:
  icon: "box"
  color: "green"
inputs:
  image_name:
    description: "The full name of the image (registry/image_name:tag)"
    required: true
  cluster-config:
    description: "The path to the kind config file"
    required: false
  registry_url:
    description: "The URL of the registry"
    required: true
    default: "ghcr.io"
  registry_username:
    description: "The username for the registry"
    required: true
  registry_token:
    description: "Token or password used to connect to the specified container registry, for ghcr.io you can use the default token: secrets.GITHUB_TOKEN"
    required: true
  command:
    description: "The command to at container startup."
    required: false
  args:
    description: "The arguments to the command."
    required: false
  env_vars:
    description: "Environment variables in YAML format"
    required: false
  port:
    description: "The port of the application"
    required: false
    default: "80"
  path:
    description: "The path to test, also used for readiness and liveness probes"
    required: false
    default: "/"
  timeoutSeconds:
    description: "Number of seconds to wait for the pod to spin up."
    required: false
    default: "20"
  initialDelaySeconds:
    description: "Number of seconds after the container has started before liveness or readiness probes are initiated."
    required: false
    default: "5"
  periodSeconds:
    description: "How often (in seconds) to perform the probe. Minimum value is 1."
    required: false
    default: "10"

runs:
  using: "composite"
  steps:
    - run: pip install pyyaml
      shell: bash

    - run: cat ${{ github.action_path }}/create_deployment.py
      shell: bash

    - run: python3 ${{ github.action_path }}/create_deployment.py
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_IMAGE_NAME: ${{ inputs.image-name }}
        INPUT_PORT: ${{ inputs.port }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_INITIALDELAYSECONDS: ${{ inputs.initialDelaySeconds }}
        INPUT_PERIODSECONDS: ${{ inputs.periodSeconds }}
        INPUT_COMMAND: ${{ inputs.command }}
        INPUT_ARGS: ${{ inputs.args }}
        INPUT_ENV_VARS: ${{ inputs.env_vars }}

    - run: |
        cat deployment.yaml
      shell: bash

    - name: Setup Kind
      uses: helm/kind-action@v1.2.0
      with:
        config: ${{ inputs.cluster-config }}

    - run: |
        kubectl cluster-info
        kubectl get nodes
      shell: bash

    - run: |
        kubectl create secret docker-registry registry-secret \
          --docker-server=${{ inputs.registry_url }} \
          --docker-username=${{ inputs.registry_username }} \
          --docker-password=${{ inputs.registry_token }}
      shell: bash

    - run: |
        kubectl apply -f sa.yaml
        kubectl apply -f crb.yaml
        kubectl apply -f deployment.yaml
        echo "Sleeping for ${{ inputs.timeoutSeconds }}s to allow the pod to fully start."
        sleep ${{ inputs.timeoutSeconds }}
        kubectl get po
        POD_NAME=$(kubectl get pod -l app=application -o jsonpath="{.items[0].metadata.name}")
        echo "Retrieving logs for $POD_NAME"
        kubectl logs $POD_NAME
        kubectl port-forward $POD_NAME 8000:${{ inputs.port }} &>/dev/null &
        sleep 5
      shell: bash

    - run: |
        curl -i http://localhost:8000${{ inputs.path }}
      shell: bash
