name: Test

on: [push]

env:
  IMAGE_NAME: "nginx"
  IMAGE_TAG: "latest"
  REGISTRY_URL: "ghcr.io"
  REGISTRY_USERNAME: "${{ github.actor }}"
  REGISTRY_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  APP_PORT: "80"
  PATH: "/"
  INITIAL_DELAY_SECONDS: "5"
  PERIOD_SECONDS: "10"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .yamllint.yml

  tester:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test Action with Sample Nginx Application
        uses: Arv1nt3/kubernetes-deployment-tester-action@main
        with:
          image_name: '${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
          registry_url: ${{ env.REGISTRY_URL }}
          registry_username: ${{ env.REGISTRY_USERNAME }}
          registry_token: ${{ env.REGISTRY_TOKEN }}
          port: ${{ env.APP_PORT }}
          path: ${{ env.PATH }}
          initialDelaySeconds: ${{ env.INITIAL_DELAY_SECONDS }}
          periodSeconds: ${{ env.PERIOD_SECONDS }}
