name: Test

on: [push]

jobs:
  test-remote-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build image and push to registry
        run: |
          docker buildx build \
            --file ./test/Dockerfile \
            --tag ghcr.io/arv1nt3/application:latest \
            --push \
            ./test

      - name: Test Action with Sample Flask Application
        uses: Arv1nt3/kubernetes-deployment-tester-action@main
        with:
          image_name: 'ghcr.io/arv1nt3/application:latest'
          use_local_image: false
          port: '5000'
          registry_token: ${{ secrets.CR_PAT }}
          registry_url: ghcr.io
          registry_username: arv1nt3
          command: 'flask'
          args: 'run,--host=0.0.0.0'
          env_vars: |
            - name: APP_KEY
              value: "YourAppKeyHere"

      - name: Remove Image from ghcr.io
        if: success()
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker rmi ghcr.io/arv1nt3/application:latest
          curl -X DELETE -u ${{ github.actor }}:${{ secrets.CR_PAT }} \
            "https://ghcr.io/v2/arv1nt3/application/manifests/latest"

  test-local-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build image and load locally
        run: |
          docker buildx build \
            --file ./test/Dockerfile \
            --tag ghcr.io/arv1nt3/application:latest \
            --load \
            ./test

      - name: Test Action with Sample Flask Application
        uses: Arv1nt3/kubernetes-deployment-tester-action@main
        with:
          image_name: 'ghcr.io/arv1nt3/application:latest'
          use_local_image: true
          port: '5000'
          registry_token: ${{ secrets.CR_PAT }}
          registry_url: ghcr.io
          registry_username: arv1nt3
          command: 'flask'
          args: 'run,--host=0.0.0.0'
          env_vars: |
            - name: APP_KEY
              value: "YourAppKeyHere"
